// models/alertConfig.js

// Static data for teams (for demo purposes)
export const STATIC_TEAMS = [
  { id: 1, name: "Team Alpha", department: "Security" },
  { id: 2, name: "Team Bravo", department: "Operations" },
  { id: 3, name: "Team Charlie", department: "Logistics" },
  { id: 4, name: "Team Delta", department: "HR" },
];

// Default alert configuration template
export const DEFAULT_ALERT_CONFIG = {
  tenant_id: "SAM001",
  team_id: null,
  config_name: "Critical Emergency Protocol",
  description: "SOS and medical emergencies for all employees",
  applicable_alert_types: ["SOS", "MEDICAL", "MEDICALS", "MEDICAL", "MEDICALS"],
  primary_recipients: [
    {
      name: "Security Control Room",
      email: "security@enterprise.com",
      phone: "+911234567890",
      role: "Security",
      channels: ["SMS", "PUSH", "EMAIL"],
    },
  ],
  enable_escalation: true,
  escalation_threshold_seconds: 120,
  escalation_recipients: [
    {
      name: "Chief Security Officer",
      email: "cso@enterprise.com",
      phone: "+911234567892",
      role: "CSO",
      channels: ["SMS", "VOICE", "EMAIL"],
    },
  ],
  notification_channels: ["EMAIL", "SMS", "PUSH", "VOICE"],
  notify_on_status_change: true,
  notify_on_escalation: true,
  auto_close_false_alarm_seconds: 90,
  require_closure_notes: true,
  enable_geofencing_alerts: true,
  geofence_radius_meters: 500,
  emergency_contacts: [
    { name: "Police", phone: "100", service_type: "POLICE" },
    { name: "Ambulance", phone: "108", service_type: "MEDICAL" },
  ],
  is_active: true,
  priority: 500,
};

// Sample data from API response
export const SAMPLE_CONFIGS = [
  {
    config_id: 1,
    tenant_id: "SAM001",
    team_id: 1,
    config_name: "Critical Emergency Protocol",
    description: "SOS and medical emergencies for all employees",
    applicable_alert_types: [
      "SOS",
      "MEDICAL",
      "SOS",
      "MEDICAHHHHHHL",
      "SOS",
      "MEDICAL",
    ],
    primary_recipients: [
      {
        name: "Security Control Room",
        email: "security@enterprise.com",
        phone: "+911234567890",
        role: "Security",
        channels: ["SMS", "PUSH", "EMAIL"],
      },
    ],
    enable_escalation: true,
    escalation_threshold_seconds: 120,
    escalation_recipients: [
      {
        name: "Chief Security Officer",
        email: "cso@enterprise.com",
        phone: "+911234567892",
        role: "CSO",
        channels: ["SMS", "VOICE", "EMAIL"],
      },
    ],
    notification_channels: ["EMAIL", "SMS", "PUSH", "VOICE"],
    notify_on_status_change: true,
    notify_on_escalation: true,
    auto_close_false_alarm_seconds: 90,
    require_closure_notes: true,
    enable_geofencing_alerts: true,
    geofence_radius_meters: 500,
    emergency_contacts: [
      { name: "Police", phone: "100", service_type: "POLICE" },
      { name: "Ambulance", phone: "108", service_type: "MEDICAL" },
    ],
    is_active: true,
    priority: 500,
    created_at: "2025-12-31T23:59:03.112639",
    updated_at: "2025-12-31T23:59:03.112639",
    created_by: "1",
    updated_by: null,
  },
  {
    config_id: 2,
    tenant_id: "SAM001",
    team_id: 2,
    config_name: "Critical Emergency Protocol",
    description: "SOS and medical emergencies for all employees",
    applicable_alert_types: ["SOS", "MEDICAL"],
    primary_recipients: [
      {
        name: "Security Control Room",
        email: "security@enterprise.com",
        phone: "+911234567890",
        role: "Security",
        channels: ["SMS", "PUSH", "EMAIL"],
      },
    ],
    enable_escalation: true,
    escalation_threshold_seconds: 120,
    escalation_recipients: [
      {
        name: "Chief Security Officer",
        email: "cso@enterprise.com",
        phone: "+911234567892",
        role: "CSO",
        channels: ["SMS", "VOICE", "EMAIL"],
      },
    ],
    notification_channels: ["EMAIL", "SMS", "PUSH", "VOICE"],
    notify_on_status_change: true,
    notify_on_escalation: true,
    auto_close_false_alarm_seconds: 90,
    require_closure_notes: true,
    enable_geofencing_alerts: true,
    geofence_radius_meters: 500,
    emergency_contacts: [
      { name: "Police", phone: "100", service_type: "POLICE" },
      { name: "Ambulance", phone: "108", service_type: "MEDICAL" },
    ],
    is_active: true,
    priority: 500,
    created_at: "2026-01-01T00:57:29.438949",
    updated_at: "2026-01-01T00:57:29.438949",
    created_by: "2",
    updated_by: null,
  },
  {
    config_id: 3,
    tenant_id: "SAM001",
    team_id: null,
    config_name: "Critical Emergency Protocol",
    description: "SOS and medical emergencies for all employees",
    applicable_alert_types: ["SOS", "MEDICAL"],
    primary_recipients: [
      {
        name: "Security Control Room",
        email: "security@enterprise.com",
        phone: "+911234567890",
        role: "Security",
        channels: ["SMS", "PUSH", "EMAIL"],
      },
    ],
    enable_escalation: true,
    escalation_threshold_seconds: 120,
    escalation_recipients: [
      {
        name: "Chief Security Officer",
        email: "cso@enterprise.com",
        phone: "+911234567892",
        role: "CSO",
        channels: ["SMS", "VOICE", "EMAIL"],
      },
    ],
    notification_channels: ["EMAIL", "SMS", "PUSH", "VOICE"],
    notify_on_status_change: true,
    notify_on_escalation: true,
    auto_close_false_alarm_seconds: 90,
    require_closure_notes: true,
    enable_geofencing_alerts: true,
    geofence_radius_meters: 500,
    emergency_contacts: [
      { name: "Police", phone: "100", service_type: "POLICE" },
      { name: "Ambulance", phone: "108", service_type: "MEDICAL" },
    ],
    is_active: true,
    priority: 500,
    created_at: "2026-01-01T01:00:35.471767",
    updated_at: "2026-01-01T01:00:35.471767",
    created_by: "2",
    updated_by: null,
  },
  {
    config_id: 4,
    tenant_id: "SAM001",
    team_id: 3,
    config_name: "Critical Emergency Potocol",
    description: "SOS and medical emergencies for all employees",
    applicable_alert_types: ["SOS", "MEDICAL"],
    primary_recipients: [
      {
        name: "Security Control Room",
        email: "security@enterprise.com",
        phone: "+911234567890",
        role: "Security",
        channels: ["SMS", "PUSH", "EMAIL"],
      },
    ],
    enable_escalation: true,
    escalation_threshold_seconds: 120,
    escalation_recipients: [
      {
        name: "Chief Security Officer",
        email: "cso@enterprise.com",
        phone: "+911234567892",
        role: "CSO",
        channels: ["SMS", "VOICE", "EMAIL"],
      },
    ],
    notification_channels: ["EMAIL", "SMS", "PUSH", "VOICE"],
    notify_on_status_change: true,
    notify_on_escalation: true,
    auto_close_false_alarm_seconds: 90,
    require_closure_notes: true,
    enable_geofencing_alerts: true,
    geofence_radius_meters: 500,
    emergency_contacts: [
      { name: "Police", phone: "100", service_type: "POLICE" },
      { name: "Ambulance", phone: "108", service_type: "MEDICAL" },
    ],
    is_active: true,
    priority: 500,
    created_at: "2026-01-02T14:01:39.757506",
    updated_at: "2026-01-02T14:01:39.757506",
    created_by: "2",
    updated_by: null,
  },
];
