// ─── Styles ───────────────────────────────────────────────────────────────────
export const S = {
  root:         { position: "relative", width: "100%", height: "100%", minHeight: 600, background: "#f1f5f9", borderRadius: 12, overflow: "hidden", fontFamily: "'DM Sans',system-ui,sans-serif" },
  map:          { position: "absolute", inset: 0, width: "100%", height: "100%" },
  sbar:         { position: "absolute", top: 12, left: "50%", transform: "translateX(-50%)", zIndex: 1500, background: "#ffffff", border: "1px solid #e2e8f0", borderRadius: 100, padding: "12px 24px", display: "flex", gap: 14, alignItems: "center", whiteSpace: "nowrap", boxShadow: "0 2px 8px rgba(0,0,0,.08)" },
  pill:         { fontSize: 11, fontWeight: 600, padding: "2px 10px", borderRadius: 100, letterSpacing: ".3px" },
  sdiv:         { color: "#e2e8f0", fontSize: 14 },
  lpanel:       { position: "absolute", top: 64, left: 12, width: 300, maxHeight: 540, zIndex: 1500, background: "#ffffff", border: "1px solid #e2e8f0", borderRadius: 12, display: "flex", flexDirection: "column", overflow: "hidden", boxShadow: "0 4px 16px rgba(0,0,0,.08)" },
  lhead:        { padding: "10px 10px 0", flexShrink: 0, background: "#ffffff" },
  chips:        { display: "flex", gap: 4, flexWrap: "wrap", marginBottom: 8, borderBottom: "1px solid #f1f5f9", paddingBottom: 8 },
  chipsLoading: { fontSize: 11, color: "#94a3b8", padding: "4px 0 8px" },
  tenantLabel:  { fontSize: 11, color: "#64748b", marginBottom: 4, textTransform: "uppercase", letterSpacing: ".08em" },
  tenantSelect: { width: "100%", appearance: "none", padding: "10px 12px", borderRadius: 10, border: "1px solid #e2e8f0", background: "#ffffff", color: "#0f172a", fontSize: 12, outline: "none" },
  tenantHelp:   { fontSize: 11, color: "#475569", background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: 10, padding: "10px 12px", marginBottom: 8 },
  tabs:         { display: "flex", gap: 3, marginBottom: 6 },
  tab:          { flex: 1, fontSize: 10, padding: "5px 0", borderRadius: 6, border: "1px solid #e2e8f0", background: "#f8fafc", color: "#94a3b8", cursor: "pointer", textAlign: "center", fontWeight: 500 },
  // ↓ uses border shorthand (not borderColor) so it doesn't conflict with S.tab's border shorthand
  tabOn:        { background: "#eff6ff", color: "#2563eb", border: "1px solid #bfdbfe", fontWeight: 600 },
  lbody:        { overflowY: "auto", flex: 1, scrollbarWidth: "thin", scrollbarColor: "#e2e8f0 transparent" },
  empty:        { fontSize: 11, color: "#94a3b8", padding: "12px 14px", fontStyle: "italic" },
  vname:        { padding: "8px 12px 2px", fontSize: 10, fontWeight: 700, letterSpacing: ".06em", textTransform: "uppercase", color: "#94a3b8" },
  drow:         { width: "100%", padding: "6px 12px", display: "flex", alignItems: "center", gap: 8, cursor: "pointer", background: "transparent", border: "none", textAlign: "left", transition: "background .1s" },
  ddot:         { width: 7, height: 7, borderRadius: "50%", flexShrink: 0, display: "inline-block" },
  ddid:         { flex: 1, minWidth: 0, fontSize: 11, fontFamily: "monospace", color: "#334155", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  ddsub:        { fontSize: 10, color: "#64748b", flexShrink: 0, whiteSpace: "nowrap" },
  dtm:          { fontSize: 10, color: "#475569", flexShrink: 0 },
  dpanel:       { position: "absolute", top: 0, right: 0, width: 270, height: "100%", zIndex: 1600, transition: "transform .22s cubic-bezier(.4,0,.2,1)" },
  dpinner:      { width: "100%", height: "100%", background: "#ffffff", borderLeft: "1px solid #e2e8f0", display: "flex", flexDirection: "column", boxShadow: "-4px 0 20px rgba(0,0,0,.06)" },
  dphead:       { padding: "14px 14px 12px", borderBottom: "1px solid #f1f5f9", display: "flex", alignItems: "center", gap: 8, flexShrink: 0, background: "#f8fafc" },
  dpx:          { background: "#ffffff", border: "1px solid #e2e8f0", borderRadius: 6, color: "#94a3b8", cursor: "pointer", padding: "3px 9px", fontSize: 12, flexShrink: 0 },
  dpbody:       { padding: "16px", overflowY: "auto", flex: 1 },
  vbadge:       { display: "inline-block", fontSize: 10, padding: "2px 10px", borderRadius: 100, fontFamily: "monospace", fontWeight: 700, marginBottom: 10, border: "1px solid transparent" },
  dprow:        { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "7px 0", borderBottom: "0.5px solid #f1f5f9" },
  legend:       { position: "absolute", bottom: 28, left: 12, zIndex: 1500, background: "rgba(5,7,12,.9)", border: "0.5px solid rgba(255,255,255,.08)", borderRadius: 8, padding: "8px 12px" },
  overlay:      { position: "absolute", inset: 0, zIndex: 2500, background: "rgba(4,6,11,.85)", display: "flex", alignItems: "center", justifyContent: "center" },
  overlayBox:   { background: "rgba(10,12,18,.97)", border: "0.5px solid rgba(255,255,255,.08)", borderRadius: 10, padding: "24px 28px", maxWidth: 320, textAlign: "center" },
  syncButton: {
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 999,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#cbd5e1",
    background: "#eff6ff",
    color: "#1d4ed8",
    cursor: "pointer",
    padding: "8px 12px",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    transition: "all .15s ease",
    whiteSpace: "nowrap",
  },
  syncButtonActive: {
    background: "#2563eb",
    color: "#ffffff",
    borderColor: "#1d4ed8",
  },
  syncMessage: {
    fontSize: 11,
    color: "#475569",
    fontFamily: "monospace",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: 220,
    display: "inline-block",
  },
};