// ─── Styles ───────────────────────────────────────────────────────────────────
export const S = {
  root: {
    position: "relative",
    width: "100%",
    height: "100%",
    minHeight: 600,
    background: "#f1f5f9",
    fontFamily: "'DM Sans',system-ui,sans-serif",
  },
  map: { position: "absolute", inset: 0, width: "100%", height: "100%" },
  statsBar: {
    position: "absolute",
    top: 12,
    left: "50%",
    transform: "translateX(-50%)",
    width: "min(100%, 980px)",
    maxWidth: 980,
    zIndex: 1500,
    display: "flex",
    gap: 10,
    alignItems: "flex-start",
    justifyContent: "space-between",
    background: "rgba(255,255,255,.95)",
    border: "1px solid #e2e8f0",
    borderRadius: 16,
    padding: "12px 14px",
    boxShadow: "0 10px 24px rgba(15,23,42,.12)",
  },
  statsGroup: { display: "flex", gap: 12, flexWrap: "wrap", flex: 1 },
  kpiCard: {
    minWidth: 120,
    flex: "1 1 120px",
    padding: "12px 14px",
    borderRadius: 14,
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    boxShadow: "0 6px 18px rgba(15,23,42,.06)",
  },
  kpiCardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  kpiIcon: { fontSize: 16, lineHeight: 1 },
  kpiLabel: {
    fontSize: 10,
    color: "#64748b",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: ".08em",
  },
  kpiValue: { fontSize: 22, fontWeight: 800, color: "#0f172a", lineHeight: 1 },
  selectedVendorCard: {
    minWidth: 180,
    maxWidth: 240,
    padding: "12px 14px",
    borderRadius: 14,
    background: "#eef4ff",
    border: "1px solid #c7d2fe",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  selectedVendorLabel: {
    fontSize: 11,
    color: "#475569",
    textTransform: "uppercase",
    letterSpacing: ".08em",
    fontWeight: 700,
  },
  selectedVendorValue: { fontSize: 15, fontWeight: 700, color: "#0f172a" },
  statusBadge: {
    marginTop: 6,
    alignSelf: "flex-start",
    padding: "6px 10px",
    borderRadius: 999,
    background: "#e0f2fe",
    color: "#0369a1",
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: ".08em",
  },
  collapseButton: {
    position: "absolute",
    right: 8,
    top: 8,
    width: 28,
    height: 28,
    borderRadius: 8,
    border: "none",
    background: "#eef2ff",
    color: "#1d4ed8",
    cursor: "pointer",
    fontWeight: 800,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  compactBar: {
    position: "absolute",
    top: 12,
    left: "50%",
    transform: "translateX(-50%)",
    width: "min(100%, 440px)",
    maxWidth: 440,
    zIndex: 1600,
    display: "flex",
    gap: 8,
    alignItems: "center",
    justifyContent: "space-between",
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 12,
    padding: "8px 10px",
    boxShadow: "0 8px 20px rgba(15,23,42,.08)",
  },
  compactLeft: { display: "flex", alignItems: "center", gap: 8 },
  compactToggle: {
    border: "none",
    background: "transparent",
    color: "#475569",
    fontSize: 16,
    cursor: "pointer",
    padding: 6,
  },
  compactIcon: {
    border: "none",
    background: "transparent",
    fontSize: 16,
    cursor: "pointer",
    padding: 6,
  },
  compactSmall: {
    padding: "6px 10px",
    borderRadius: 8,
    border: "1px solid #e2e8f0",
    background: "#f8fafc",
    color: "#475569",
    fontSize: 12,
    cursor: "pointer",
  },
  sbar: {
    position: "absolute",
    top: 12,
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 1500,
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 100,
    padding: "12px 24px",
    display: "flex",
    gap: 14,
    alignItems: "center",
    whiteSpace: "nowrap",
    boxShadow: "0 2px 8px rgba(0,0,0,.08)",
  },
  pill: {
    fontSize: 11,
    fontWeight: 600,
    padding: "2px 10px",
    borderRadius: 100,
    letterSpacing: ".3px",
  },
  sdiv: { color: "#e2e8f0", fontSize: 14 },
  lpanel: {
    position: "absolute",
    top: 72,
    left: 12,
    width: 260,
    maxHeight: 520,
    zIndex: 1500,
    background: "#eef4fb",
    border: "1px solid #cbd5e1",
    borderRadius: 14,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    boxShadow: "0 8px 20px rgba(15, 23, 42, .16)",
  },
  lhead: { padding: "10px 10px 0", flexShrink: 0, background: "#eef4fb" },
  chips: {
    display: "flex",
    gap: 4,
    flexWrap: "wrap",
    marginBottom: 8,
    borderBottom: "1px solid #dbeafe",
    paddingBottom: 6,
  },
  chipsLoading: { fontSize: 11, color: "#475569", padding: "4px 0 8px" },
  tenantLabel: {
    fontSize: 11,
    color: "#475569",
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: ".08em",
  },
  tenantSelect: {
    width: "100%",
    appearance: "none",
    padding: "10px 12px",
    borderRadius: 10,
    border: "1px solid #cbd5e1",
    background: "#ffffff",
    color: "#0f172a",
    fontSize: 12,
    outline: "none",
  },
  tenantHelp: {
    fontSize: 11,
    color: "#475569",
    background: "#f8fafc",
    border: "1px solid #cbd5e1",
    borderRadius: 10,
    padding: "10px 12px",
    marginBottom: 8,
  },
  sidebarTitle: {
    fontSize: 13,
    fontWeight: 800,
    color: "#0f172a",
    marginBottom: 10,
  },
  sidebarSearch: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: 12,
    border: "1px solid #cbd5e1",
    background: "#ffffff",
    color: "#0f172a",
    fontSize: 12,
    outline: "none",
    marginBottom: 12,
  },
  vendorSummary: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    marginBottom: 12,
  },
  vendorCard: {
    width: "100%",
    borderRadius: 14,
    border: "1px solid #e2e8f0",
    background: "#ffffff",
    padding: "12px 14px",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    textAlign: "left",
    cursor: "pointer",
    transition: "background .15s, border-color .15s",
  },
  vendorCardActive: { background: "#eff6ff", border: "1px solid #bfdbfe" },
  vendorCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  vendorCardLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    fontWeight: 700,
    color: "#0f172a",
  },
  vendorCardTotal: { fontSize: 13, fontWeight: 700, color: "#0f172a" },
  vendorCardCounts: { display: "flex", gap: 8, flexWrap: "wrap" },
  vendorCountBadge: {
    fontSize: 11,
    padding: "4px 8px",
    borderRadius: 999,
    background: "#f8fafc",
    color: "#475569",
  },
  vendorCountBadgeActive: { background: "#e0f2fe", color: "#0369a1" },
  vendorCountBadgeOffline: { background: "#fee2e2", color: "#b91c1c" },
  tabs: { display: "flex", gap: 4, marginBottom: 6 },
  tab: {
    flex: 1,
    fontSize: 10,
    padding: "6px 0",
    borderRadius: 8,
    border: "1px solid #cbd5e1",
    background: "#f1f5f9",
    color: "#475569",
    cursor: "pointer",
    textAlign: "center",
    fontWeight: 600,
  },
  tabOn: {
    background: "#dbeafe",
    color: "#1d4ed8",
    border: "1px solid #bfdbfe",
    fontWeight: 700,
  },
  lbody: {
    overflowY: "auto",
    flex: 1,
    scrollbarWidth: "thin",
    scrollbarColor: "#cbd5e1 transparent",
  },
  empty: {
    fontSize: 11,
    color: "#475569",
    padding: "12px 14px",
    fontStyle: "italic",
  },
  vname: {
    padding: "6px 10px 2px",
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: ".06em",
    textTransform: "uppercase",
    color: "#334155",
  },
  drow: {
    width: "100%",
    padding: "6px 10px",
    display: "flex",
    alignItems: "center",
    gap: 6,
    cursor: "pointer",
    background: "transparent",
    border: "none",
    textAlign: "left",
    transition: "background .12s",
    color: "#0f172a",
  },
  ddot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    flexShrink: 0,
    display: "inline-block",
  },
  ddid: {
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    fontFamily: "monospace",
    color: "#0f172a",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  ddsub: {
    fontSize: 10,
    color: "#334155",
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
  dtm: { fontSize: 10, color: "#334155", flexShrink: 0 },
  dpanel: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 270,
    height: "100%",
    zIndex: 1600,
    transition: "transform .22s cubic-bezier(.4,0,.2,1)",
  },
  dpinner: {
    width: "100%",
    height: "100%",
    background: "#ffffff",
    borderLeft: "1px solid #e2e8f0",
    display: "flex",
    flexDirection: "column",
    boxShadow: "-4px 0 20px rgba(0,0,0,.06)",
  },
  dphead: {
    padding: "14px 14px 12px",
    borderBottom: "1px solid #f1f5f9",
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
    background: "#f8fafc",
  },
  dpx: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 6,
    color: "#94a3b8",
    cursor: "pointer",
    padding: "3px 9px",
    fontSize: 12,
    flexShrink: 0,
  },
  dpbody: { padding: "16px", overflowY: "auto", flex: 1 },
  vbadge: {
    display: "inline-block",
    fontSize: 10,
    padding: "2px 10px",
    borderRadius: 100,
    fontFamily: "monospace",
    fontWeight: 700,
    marginBottom: 10,
    border: "1px solid transparent",
  },
  dprow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "7px 0",
    borderBottom: "0.5px solid #f1f5f9",
  },
  legend: {
    position: "absolute",
    bottom: 28,
    left: 12,
    zIndex: 1500,
    background: "rgba(5,7,12,.9)",
    border: "0.5px solid rgba(255,255,255,.08)",
    borderRadius: 8,
    padding: "8px 12px",
  },
  overlay: {
    position: "absolute",
    inset: 0,
    zIndex: 2500,
    background: "rgba(4,6,11,.85)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  overlayBox: {
    background: "rgba(10,12,18,.97)",
    border: "0.5px solid rgba(255,255,255,.08)",
    borderRadius: 10,
    padding: "24px 28px",
    maxWidth: 320,
    textAlign: "center",
  },
  syncButton: {
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 999,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#cbd5e1",
    background: "#eff6ff",
    color: "#1d4ed8",
    cursor: "pointer",
    padding: "8px 12px",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    transition: "all .15s ease",
    whiteSpace: "nowrap",
  },
  syncButtonActive: {
    background: "#2563eb",
    color: "#ffffff",
    borderColor: "#1d4ed8",
  },
  syncMessage: {
    fontSize: 11,
    color: "#475569",
    fontFamily: "monospace",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: 220,
    display: "inline-block",
  },
};
