
export const vehicleContractDummyData = [
  {
    id: 1,
    name: 'SEDAN',
    cabType: 'SEDAN',
    shortCode: 'SED',
    contractType: 'TRIP_PACKAGE_BASED',
    autoCorrect: true,
    disabled: false,
    autoAudit: true,
    garageCalculation: false,
    numberOfDuties: 30,
    allottedKmPerMonth: 2500,
    minimumHoursPerDay: 8,
    garageKmOffDuty: 5,
    garageKmOnDuty: 5,
    garageHoursPerDay: 0.5,
    packageCostPerMonth: 40000,
    pricingForExtraDuty: 'Hourly',
    costPerKm: 10.0,
    costPerHour: 120.0,
    baseDieselPrice: 90.0,
    mileage: 15.0,
    seatingCapacity: 4,
    acPriceAdjustmentPerKm: 0.5,
    minimumTripsPerMonth: 25,
    dieselPriceWindows: [
      { startDate: '06/01/2025', endDate: '06/30/2025', price: 92 },
      { startDate: '07/01/2025', endDate: '07/31/2025', price: 94 },
    ],
    comment: 'Suitable for daily city travel.',
    history: [],
  },
  {
    id: 2,
    name: 'SEDAN_WOMENS',
    cabType: 'SEDAN',
    shortCode: 'SW',
    contractType: 'TRIP_PACKAGE_BASED',
    autoCorrect: true,
    disabled: false,
    autoAudit: false,
    garageCalculation: false,
    numberOfDuties: 22,
    allottedKmPerMonth: 1800,
    minimumHoursPerDay: 7,
    garageKmOffDuty: 4,
    garageKmOnDuty: 3,
    garageHoursPerDay: 0.3,
    packageCostPerMonth: 35000,
    pricingForExtraDuty: 'KM Only',
    costPerKm: 9.0,
    costPerHour: 100.0,
    baseDieselPrice: 89.0,
    mileage: 16.0,
    seatingCapacity: 4,
    acPriceAdjustmentPerKm: 0.4,
    minimumTripsPerMonth: 15,
    dieselPriceWindows: [
      { startDate: '05/01/2025', endDate: '05/31/2025', price: 90 },
    ],
    comment: "Optimized contract for women's safety.",
    history: [],
  },
  {
    id: 3,
    name: 'SUV Premium',
    cabType: 'SUV',
    shortCode: 'SUVP',
    contractType: 'TRIP_PACKAGE_BASED',
    autoCorrect: false,
    disabled: false,
    autoAudit: true,
    garageCalculation: true,
    numberOfDuties: 26,
    allottedKmPerMonth: 3000,
    minimumHoursPerDay: 10,
    garageKmOffDuty: 8,
    garageKmOnDuty: 7,
    garageHoursPerDay: 1.0,
    packageCostPerMonth: 60000,
    pricingForExtraDuty: 'Hourly + KM',
    costPerKm: 12.5,
    costPerHour: 150.0,
    baseDieselPrice: 91.5,
    mileage: 10.0,
    seatingCapacity: 7,
    acPriceAdjustmentPerKm: 0.75,
    minimumTripsPerMonth: 20,
    dieselPriceWindows: [
      { startDate: '06/01/2025', endDate: '07/01/2025', price: 92 },
      { startDate: '07/02/2025', endDate: '08/01/2025', price: 95 },
    ],
    comment: 'Premium SUV with full-time AC usage.',
    history: [],
  },
];
