  export const VehicleTableDatadummyData = [
    {
      id: 1,
      registration: 'KA-41-AA-0532',
      etsId: '1057',
      displayId: 'MLT - 0532',
      startDate: '22-05-2025',
      startTime: '00:00:00',
      endTime: '23:59:59',
      contract: 'SEDAN',
      dayType: 'ALL',
      office: 'ALL',
      tripType: 'DEFAULT',
    },
    {
      id: 2,
      registration: 'KA-01-AR-3016',
      etsId: '1058',
      displayId: 'MLT - 3016',
      startDate: '22-05-2025',
      startTime: '00:00:00',
      endTime: '23:59:59',
      contract: 'SEDAN_WOMENS',
      dayType: 'ALL',
      office: 'ALL',
      tripType: 'DEFAULT',
    },
    {
      id: 3,
      registration: 'KA-41-C-0531',
      etsId: '1024',
      displayId: 'MLT - 0531',
      startDate: '22-05-2025',
      startTime: '00:00:00',
      endTime: '23:59:59',
      contract: 'SEDAN_WOMENS',
      dayType: 'ALL',
      office: 'ALL',
      tripType: 'DEFAULT',
    },
    {
      id: 4,
      registration: 'KA-04-AE-6991',
      etsId: '991',
      displayId: 'MLT - 6991',
      startDate: '20-05-2025',
      startTime: '00:00:00',
      endTime: '23:59:59',
      contract: 'SEDAN_WOMENS',
      dayType: 'ALL',
      office: 'ALL',
      tripType: 'DEFAULT',
    },
    {
      id: 5,
      registration: 'KA-03-AJ-3430',
      etsId: '40',
      displayId: 'MLT - 3430',
      startDate: '20-05-2025',
      startTime: '00:00:00',
      endTime: '23:59:59',
      contract: 'SEDAN',
      dayType: 'ALL',
      office: 'ALL',
      tripType: 'DEFAULT',
    },
    {
      id: 6,
      registration: 'KA-05-AQ-2178',
      etsId: '793',
      displayId: 'MLT - 2178',
      startDate: '19-05-2025',
      startTime: '00:00:00',
      endTime: '23:59:59',
      contract: 'SEDAN',
      dayType: 'ALL',
      office: 'ALL',
      tripType: 'DEFAULT',
    },
    {
      id: 7,
      registration: 'KA-05-AQ-2178',
      etsId: '793',
      displayId: 'MLT - 2178',
      startDate: '19-05-2025',
      startTime: '00:00:00',
      endTime: '23:59:59',
      contract: 'SEDAN',
      dayType: 'ALL',
      office: 'ALL',
      tripType: 'DEFAULT',
    },
    {
      id: 8,
      registration: 'KA-05-AQ-2178',
      etsId: '793',
      displayId: 'MLT - 2178',
      startDate: '19-05-2025',
      startTime: '00:00:00',
      endTime: '23:59:59',
      contract: 'SEDAN',
      dayType: 'ALL',
      office: 'ALL',
      tripType: 'DEFAULT',
    },
    {
      id: 9,
      registration: 'KA-05-AQ-2178',
      etsId: '793',
      displayId: 'MLT - 2178',
      startDate: '19-05-2025',
      startTime: '00:00:00',
      endTime: '23:59:59',
      contract: 'SEDAN',
      dayType: 'ALL',
      office: 'ALL',
      tripType: 'DEFAULT',
    },
    {
      id: 10,
      registration: 'KA-05-AQ-2178',
      etsId: '793',
      displayId: 'MLT - 2178',
      startDate: '19-05-2025',
      startTime: '00:00:00',
      endTime: '23:59:59',
      contract: 'SEDAN',
      dayType: 'ALL',
      office: 'ALL',
      tripType: 'DEFAULT',
    },
  ];

   export const VehicleTableheaders = [
    { key: 'registration', label: 'Vehicle Registration' },
    { key: 'etsId', label: 'Ets Vehicle ID' },
    { key: 'displayId', label: 'Vehicle Display ID' },
    { key: 'startDate', label: 'Start Date' },
    { key: 'startTime', label: 'Start Time' },
    { key: 'endTime', label: 'End Time' },
    { key: 'contract', label: 'Contract' },
    { key: 'dayType', label: 'Day Type' },
    { key: 'office', label: 'Office' },
    { key: 'tripType', label: 'Trip Type' },
  ];

