// dummyData.js
export const dummyRoutes = [
  {
    route_id: "RT001",
    log_type: "Scheduled",
    shift_id: "SH001",
    shift_time: "Morning (6:00 AM - 2:00 PM)",
    driver: {
      id: "DR001",
      name: "Rajesh Kumar",
      phone: "+91 9876543210",
    },
    vehicle: {
      id: "VH001",
      rc_number: "KA01AB1234",
      type: "SUV",
      capacity: 6,
    },
    vendor: {
      id: "VEN001",
      name: "City Cab Services",
      contact: "+91 9876543211",
    },
    summary: {
      total_distance_km: 45.2,
      total_time_minutes: 128,
      total_stops: 8,
      fuel_cost: 1200,
      efficiency: "Good",
    },
    estimations: {
      total_distance_km: 45.2,
      total_time_minutes: 128,
      estimated_pickup_times: {
        BK001: "06:15 AM",
        BK002: "06:45 AM",
        BK003: "07:20 AM",
        BK004: "08:00 AM",
        BK005: "08:35 AM",
        BK006: "09:15 AM",
        BK007: "09:50 AM",
        BK008: "10:30 AM",
      },
      estimated_drop_times: {
        BK001: "07:00 AM",
        BK002: "07:35 AM",
        BK003: "08:15 AM",
        BK004: "08:55 AM",
        BK005: "09:40 AM",
        BK006: "10:20 AM",
        BK007: "11:05 AM",
        BK008: "11:45 AM",
      },
    },
    bookings: [
      {
        booking_id: "BK001",
        employee_code: "EMP00123",
        employee_name: "Amit Sharma",
        pickup_location: "HSR Layout, Sector 2",
        drop_location: "Electronic City, Phase 1",
        pickup_time: "06:15 AM",
        drop_time: "07:00 AM",
        status: "confirmed",
        special_requirements: "None",
      },
      {
        booking_id: "BK002",
        employee_code: "EMP00145",
        employee_name: "Priya Singh",
        pickup_location: "Koramangala, 5th Block",
        drop_location: "Whitefield, ITPL",
        pickup_time: "06:45 AM",
        drop_time: "07:35 AM",
        status: "confirmed",
        special_requirements: "Wheelchair accessible",
      },
      {
        booking_id: "BK003",
        employee_code: "EMP00167",
        employee_name: "Rohit Verma",
        pickup_location: "BTM Layout, 2nd Stage",
        drop_location: "Manyata Tech Park",
        pickup_time: "07:20 AM",
        drop_time: "08:15 AM",
        status: "confirmed",
        special_requirements: "Early pickup required",
      },
      {
        booking_id: "BK004",
        employee_code: "EMP00189",
        employee_name: "Neha Patel",
        pickup_location: "Jayanagar, 4th Block",
        drop_location: "Sarjapur Road",
        pickup_time: "08:00 AM",
        drop_time: "08:55 AM",
        status: "confirmed",
        special_requirements: "None",
      },
    ],
  },
  {
    route_id: "RT002",
    log_type: "Optimized",
    shift_id: "SH002",
    shift_time: "Evening (2:00 PM - 10:00 PM)",
    driver: {
      id: "DR002",
      name: "Suresh Nair",
      phone: "+91 9876543212",
    },
    vehicle: {
      id: "VH002",
      rc_number: "KA01CD5678",
      type: "Sedan",
      capacity: 4,
    },
    vendor: {
      id: "VEN002",
      name: "Metro Transport",
      contact: "+91 9876543213",
    },
    summary: {
      total_distance_km: 38.7,
      total_time_minutes: 95,
      total_stops: 6,
      fuel_cost: 980,
      efficiency: "Excellent",
    },
    estimations: {
      total_distance_km: 38.7,
      total_time_minutes: 95,
      estimated_pickup_times: {
        BK009: "02:15 PM",
        BK010: "02:50 PM",
        BK011: "03:25 PM",
        BK012: "04:05 PM",
        BK013: "04:40 PM",
        BK014: "05:20 PM",
      },
      estimated_drop_times: {
        BK009: "03:00 PM",
        BK010: "03:40 PM",
        BK011: "04:20 PM",
        BK012: "05:05 PM",
        BK013: "05:45 PM",
        BK014: "06:30 PM",
      },
    },
    bookings: [
      {
        booking_id: "BK009",
        employee_code: "EMP00234",
        employee_name: "Karthik Reddy",
        pickup_location: "Indiranagar, 100 Feet Road",
        drop_location: "Kundalahalli",
        pickup_time: "02:15 PM",
        drop_time: "03:00 PM",
        status: "confirmed",
        special_requirements: "Pet friendly",
      },
      {
        booking_id: "BK010",
        employee_code: "EMP00256",
        employee_name: "Deepa Iyer",
        pickup_location: "MG Road, Brigade Road",
        drop_location: "Marathahalli",
        pickup_time: "02:50 PM",
        drop_time: "03:40 PM",
        status: "confirmed",
        special_requirements: "None",
      },
      {
        booking_id: "BK011",
        employee_code: "EMP00278",
        employee_name: "Vikram Malhotra",
        pickup_location: "Lavelle Road",
        drop_location: "Bellandur",
        pickup_time: "03:25 PM",
        drop_time: "04:20 PM",
        status: "confirmed",
        special_requirements: "Extra luggage",
      },
    ],
  },
  {
    route_id: "RT003",
    log_type: "Emergency",
    shift_id: "SH003",
    shift_time: "Night (10:00 PM - 6:00 AM)",
    driver: {
      id: "DR003",
      name: "Anil Joshi",
      phone: "+91 9876543214",
    },
    vehicle: {
      id: "VH003",
      rc_number: "KA01EF9012",
      type: "MPV",
      capacity: 8,
    },
    vendor: {
      id: "VEN001",
      name: "City Cab Services",
      contact: "+91 9876543211",
    },
    summary: {
      total_distance_km: 52.8,
      total_time_minutes: 145,
      total_stops: 5,
      fuel_cost: 1500,
      efficiency: "Average",
    },
    estimations: {
      total_distance_km: 52.8,
      total_time_minutes: 145,
      estimated_pickup_times: {
        BK015: "10:15 PM",
        BK016: "11:00 PM",
        BK017: "12:05 AM",
        BK018: "01:20 AM",
        BK019: "02:45 AM",
      },
      estimated_drop_times: {
        BK015: "11:30 PM",
        BK016: "12:20 AM",
        BK017: "01:35 AM",
        BK018: "03:00 AM",
        BK019: "04:25 AM",
      },
    },
    bookings: [
      {
        booking_id: "BK015",
        employee_code: "EMP00345",
        employee_name: "Sanjay Gupta",
        pickup_location: "Hebbal",
        drop_location: "Airport",
        pickup_time: "10:15 PM",
        drop_time: "11:30 PM",
        status: "urgent",
        special_requirements: "Flight at 1:00 AM",
      },
      {
        booking_id: "BK016",
        employee_code: "EMP00367",
        employee_name: "Meera Krishnan",
        pickup_location: "Yeshwanthpur",
        drop_location: "Railway Station",
        pickup_time: "11:00 PM",
        drop_time: "12:20 AM",
        status: "urgent",
        special_requirements: "Train at 1:30 AM",
      },
    ],
  },
];
