import { Calendar, MapPin, TrendingUp, Users } from "lucide-react";

export const reportModules = [
  {
    id: "bookings",
    title: "Booking Reports",
    description: "Track and analyze booking data",
    icon: Calendar,
    color: "blue",
  },
];

export const REPORT_TYPES = {
  BOOKING: "bookings",
  ROUTE: "route",
  VENDOR: "vendor",
  DRIVER: "driver",
};

export const BOOKING_STATUS_OPTIONS = [
  "Request",
  "Scheduled",
  "Confirmed",
  "Completed",
  "Cancelled",
];
export const ROUTE_STATUS_OPTIONS = [
  "Pending",
  "In Progress",
  "Completed",
  "Cancelled",
];

export const DUMMY_VENDOR_USERS = [
  {
    id: 1,
    name: "John Smith",
    email: "john.smith@example.com",
    phone: "1234567890",
    vendor_id: 101,
    vendor_name: "ABC Suppliers",
    is_active: true,
    created_at: "2024-01-15T10:30:00Z",
    company_id: 1,
    company_name: "Tech Corp",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    email: "sarah.j@example.com",
    phone: "9876543210",
    vendor_id: 102,
    vendor_name: "XYZ Distributors",
    is_active: true,
    created_at: "2024-01-20T14:45:00Z",
    company_id: 1,
    company_name: "Tech Corp",
  },
  {
    id: 3,
    name: "Mike Wilson",
    email: "mike.wilson@example.com",
    phone: "5551234567",
    vendor_id: 103,
    vendor_name: "Global Logistics",
    is_active: false,
    created_at: "2024-02-01T09:15:00Z",
    company_id: 2,
    company_name: "Retail Inc",
  },
  {
    id: 4,
    name: "Emma Davis",
    email: "emma.d@example.com",
    phone: "4445556666",
    vendor_id: 104,
    vendor_name: "Premium Supplies",
    is_active: true,
    created_at: "2024-02-10T11:20:00Z",
    company_id: 2,
    company_name: "Retail Inc",
  },
  {
    id: 5,
    name: "Robert Brown",
    email: "robert.b@example.com",
    phone: "7778889999",
    vendor_id: 105,
    vendor_name: "Quality Goods Co",
    is_active: true,
    created_at: "2024-02-15T16:30:00Z",
    company_id: 3,
    company_name: "Manufacturing Ltd",
  },
  {
    id: 6,
    name: "Lisa Anderson",
    email: "lisa.a@example.com",
    phone: "3332221111",
    vendor_id: 106,
    vendor_name: "Fast Delivery Inc",
    is_active: false,
    created_at: "2024-02-20T13:45:00Z",
    company_id: 3,
    company_name: "Manufacturing Ltd",
  },
  {
    id: 7,
    name: "David Miller",
    email: "david.m@example.com",
    phone: "6667778888",
    vendor_id: 107,
    vendor_name: "Eco Supplies",
    is_active: true,
    created_at: "2024-03-01T08:00:00Z",
    company_id: 1,
    company_name: "Tech Corp",
  },
  {
    id: 8,
    name: "Jennifer Taylor",
    email: "jennifer.t@example.com",
    phone: "2223334444",
    vendor_id: 108,
    vendor_name: "Office Essentials",
    is_active: true,
    created_at: "2024-03-05T15:20:00Z",
    company_id: 2,
    company_name: "Retail Inc",
  },
];
